import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Nav from "./components/nav";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Deborah Tsarvousis, coil ceramics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="background">
          <div className='header'>
            <Header />
            </div>
            <div className='nav'>
              <Nav />
              </div>
              <div className='main-area '>
        {children}
        </div>
        <div className="footer"> 
          <Footer />
        </div>
        </div>


      </body>
    </html>
  );
}
